### ISSUE TITLE
Question about CSP and Mixed content for bookmarklets.

### ISSUE THREAD

**Issue by mikhoul** [mems/bookmarklets-context-menu#14]
Could you tell me if Bookmarklet used through this addon are supposed to work if some JS ressource is on an HTTP (non secured) server ? 

I don't remember if the addon is supposed to give this privilege ? 

If not do you know of any other addon that can bypass the CSP and "Mixed content" only for my bookmarklet to stay secure ? 

N.B.: In the past I used this addon https://addons.mozilla.org/en-US/firefox/addon/toggle-mixed-active-content/reviews/ but with Firefox 57 it will not work anymore sadly.

Regards :octocat:

**Comment by mems** [comment]
By default there is no mechanism to allow WebExtension to inject resources (other than content scripts) without same rules applied to website authors (CSP, mixed content, cross domain without CORS).
Workaround still possible, but often need to rewrite the bookmarklet script to load resources differently.

It's not adviced to load a HTTP resource in HTTPS page, because it's insecure (with HTTPS there is a kind of integrity check): [Mixed content - Web security | MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).
With Firefox 55+, there is [an exception](https://bugzilla.mozilla.org/show_bug.cgi?id=903966): mixed content is allowed only for loaded resource from localhost origin.
