### ISSUE TITLE
Does not work in calendar.google.com

### ISSUE THREAD

**Issue by AdKiller** [mems/bookmarklets-context-menu#17]
I used to use a great bookmarklet that added events to Google Calendar from any page using the highlighted text.

It stopped working ever since Google enforced that security thing.

I tried this addon to see if it would work again, but it did not.

The script opened a Google Calendar popup but could not enter the highlighted text as the title of event.

here is the bookmarklet:
`javascript:%20var%20s;/*Figure%20out%20the%20selected%20text*/if%20(%20window.getSelection%20)%20{s%20=%20window.getSelection();}%20else%20if%20(%20document.getSelection%20)%20{s%20=%20document.getSelection();}%20else%20{s%20=%20document.selection.createRange().text;}/*If%20there%20isn't%20any%20text%20selected,%20get%20user%20input*/if%20(%20s%20==%20''%20)%20{s%20=%20prompt('QuickAdd');}var%20re%20=%20RegExp(%20'[AaPp][Mm]'%20);if%20(%20encodeURIComponent(s).match(re)%20)%20{}%20else%20{var%20d%20=%20new%20Date();var%20hr%20=%20d.getHours();var%20min%20=%20d.getMinutes();if%20(min%20<%2010)%20{min%20=%20"0"%20+%20min;}s%20=%20s%20+%20"%20"%20+%20hr%20+%20":"%20+%20min;%20/*if%20there%20isn't%20an%20AM%20or%20PM%20in%20the%20text,%20add%20the%20default%20current%20time*/}void(/*open%20a%20new%20window%20with%20this%20information%20in%20the%20Google%20Calendar%20event%20creation%20page.*/window.open(encodeURI('http://www.google.com/calendar/event?ctext='+s+'&action=TEMPLATE&pprop=HowCreated:QUICKADD'),'addwindow','status=no,toolbar=no,width=520,height=470,resizable=yes'));`

**Comment by mems** [comment]
If you don't see the popup, it's because your [browser popup blocker](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting) is active. A bookmarklet (or any other page scripts) can't open a popup without be executed by a user click in the page, else otherwise the popup will be blocked. Sadly this extension can't do anything for that

I clean up a bit the bookmarlet for intelligibility (remove comments and spaces) and fix the URL of Google calendar (for the event title part) and it works (if you click on blocked popup in the Yellow bar of Firefox):

```
javascript:var%20s;if(window.getSelection){s=window.getSelection();}else%20if(document.getSelection){s=document.getSelection();}else{s=document.selection.createRange().text;}if(s==''){prompt('QuickAdd');}var%20re=RegExp('[AaPp][Mm]');if%20(encodeURIComponent(s).match(re)){}else{var%20d=new%20Date();var%20hr=d.getHours();var%20min=d.getMinutes();if%20(min<10){min="0"+min;}s=s+"%20"+hr+":"+min;}void(window.open(encodeURI('https://www.google.com/calendar/event?text='+s+'&action=TEMPLATE&pprop=HowCreated:QUICKADD'),'addwindow','status=no,toolbar=no,width=520,height=470,resizable=yes'));
```

If you need to open the popup without been blocked, you need to rewrite this bookmarklet to [show a button instead](https://stackoverflow.com/questions/4609936/how-a-bookmarklet-can-avoid-the-popup-blocker/12066782#12066782), then you could click on it to open the popup each time you use the bookmarklet
