### ISSUE TITLE
Squirt support?

### ISSUE THREAD

**Issue by lnicola** [mems/bookmarklets-context-menu#7]
Doesn't seem to work with https://squirt.io: `TypeError: sq is undefined frame.outer.js:380:1`.

**Comment by mems** [comment]
On which website do you use this bookmarklet?
I tried the provided example : https://zenhabits.net/ I it's works for me

**Comment by lnicola** [comment]
For me it doesn't. I'm on Nightly, I'll have to try on another version.

**Comment by mems** [comment]
Never mind, I didn't test with the extension, but directly from the bookmark menu

**Comment by lnicola** [comment]
It doesn't work for me from the menu because of https://github.com/cameron/squirt/issues/181, which is how I discovered your extension.

**Comment by mems** [comment]
[CSP is a problem](https://github.com/mems/bookmarklets-context-menu/wiki) that bookmarklets-context-menu try to reduce, but would give you an other kind of error like : `Content Security Policy: The page's settings blocked the loading of a resource at self`

**Comment by lnicola** [comment]
Just to make sure, does that bookmarklet work for you after b03b3709562c1dace5bdb05a2fdb276a7252178e?

**Comment by mems** [comment]
@lnicola Yes it's now work on page without CSP, but it's still doesn't work on page with CSP (like https://github.com or https://facebook.com log an kind of error `Content Security Policy: The page's settings blocked the loading of a resource at [...]`). Because Squirt load a subresource, but sadly (as you can read it on the [README](https://github.com/mems/bookmarklets-context-menu/blob/master/README.md)):
> **CSP still applied to subresources** (like scripts, styles, medias, etc.). That means with a super strict CSP "none", you can't use any additional scripts, styles nor medias.

**Comment by lnicola** [comment]
I don't get CSP errors, but `squirt.io` doesn't work for me.

> Because Squirt load a subresource

Oh, all right, then.
